services:
  db:
    ports:
      - 5432:5432
    container_name: postgresql_container
    image: postgres
    environment:
      - POSTGRES_DB=MYDB
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
  backend:
    build: .
    container_name: app_container
    ports:
      - 8080:8080
    environment:
      db-url: jdbc:postgresql://db:5432/MYDB
      db-username: root
      db_password: root
    depends_on:
      - db
    restart: always